language: php
php:
  - 5.3
  - 5.4

before_script:
  - ./scripts/bundle-devtools.sh .
  - export SUIN_QIITAME_TEST_DB_HOST=127.0.0.1
  - export SUIN_QIITAME_TEST_DB_USER=root
  - export SUIN_QIITAME_TEST_DB_PASS=""
  - mysql -e 'create database suin_qiitame_test'
script: ./vendor/bin/phpunit --coverage-text --configuration phpunit.xml.dist
